// Catálogo da Loja da Trapaça — NÃO vem do Firestore (MIGRACAO-REACT-FIREBASE.md
// §4: "nenhuma coleção equivalente ... permanecem embutidas"). É conteúdo
// autoral, embutido no código, servindo como ponto de partida representativo
// das categorias descritas em FUNCIONALIDADES.md §15 — editável aqui conforme
// a mesa quiser expandir.

export const CATEGORIAS_TRAPACA = {
  'Benefícios Menores': {
    icone: '⭐',
    cor: '#f4dda2',
    subtitulo: 'Efeitos imediatos e rápidos (Pode utilizar à vontade!)',
  },
  'Vantagens Táticas': {
    icone: '🎯',
    cor: '#f87171',
    subtitulo: 'Guardadas para usar estrategicamente (até 2)',
  },
  'Efeitos Avançados': {
    icone: '✨',
    cor: '#5b7cfa',
    subtitulo: 'Poderosos, 1 por combate',
  },
  'Bênçãos Únicas': {
    icone: '😈',
    cor: '#fb923c',
    subtitulo: 'Raras e poderosas, 1 por sessão!',
  },
};

export const CATALOGO_TRAPACA = [
  // ── Benefícios Menores — ilimitados, ativação imediata ──
  {
    id: 'encontro-favoravel',
    categoria: 'Benefícios Menores',
    icone: '💬',
    nome: 'Encontro Favorável',
    custo: 3,
    descricao: 'Rola 1d4 para reduzir obstáculo em interação social antes que saia do controle.',
    efeito: 'Reduz obstáculo em interação social',
    tags: ['narrativo', 'Imediato'],
    tipoAtivacao: 'imediata',
  },
  {
    id: 'fofoca-do-dia',
    categoria: 'Benefícios Menores',
    icone: '🎭',
    nome: 'Fofoca do Dia',
    custo: 5,
    descricao: 'Descobre uma pista ou informação útil sem exigir investigação.',
    efeito: '+1 Pista/Informação',
    tags: ['narrativo', 'Imediato'],
    tipoAtivacao: 'imediata',
  },
  {
    id: 'pressentimento',
    categoria: 'Benefícios Menores',
    icone: '🎲',
    nome: 'Pressentimento',
    custo: 5,
    descricao:
      'Antes de entrar em um local ou situação perigosa, o mestre indica dicas de um perigo próximo (emboscada, armadilha, inimigo escondido). Não revela tudo, apenas o risco mais próximo.',
    efeito: 'Aviso de perigo próximo',
    tags: ['narrativo', 'Imediato'],
    tipoAtivacao: 'imediata',
  },
  {
    id: 'momento-dramatico',
    categoria: 'Benefícios Menores',
    icone: '🎭',
    nome: 'Momento Dramático',
    custo: 6,
    descricao:
      'Uma situação social que estava prestes a dar errado recebe uma reviravolta favorável (alguém interrompe, surge prova inesperada, aliado defende). O conflito não desaparece, mas a tensão diminui.',
    efeito: 'Reviravolta em situação social',
    tags: ['narrativo', 'Imediato'],
    tipoAtivacao: 'imediata',
  },
  {
    id: 'reputacao-fervorosa',
    categoria: 'Benefícios Menores',
    icone: '👑',
    nome: 'Reputação Fervorosa',
    custo: 10,
    descricao:
      'Personagem é reconhecido por feitos notórios, facilitando ajuda social e reduzindo desconfiança inicial em novos contatos.',
    efeito: 'Facilita ajuda social',
    tags: ['narrativo', 'Imediato'],
    tipoAtivacao: 'imediata',
  },

  // ── Vantagens Táticas — limite de 2 simultâneas, armazenável ──
  {
    id: 'beneficio-ocasional',
    categoria: 'Vantagens Táticas',
    icone: '✨',
    nome: 'Benefício Ocasional',
    custo: 5,
    descricao: 'Concede +3 em uma rolagem como fator externo favorável.',
    efeito: '+3 em 1 rolagem (combate ou fora)',
    tags: ['mecânico', 'Armazenável'],
    tipoAtivacao: 'manual',
  },
  {
    id: 'ajuste-de-destino',
    categoria: 'Vantagens Táticas',
    icone: '⚔️',
    nome: 'Ajuste de Destino',
    custo: 8,
    descricao:
      'Após rolar um dado, o jogador pode aumentar ou diminuir o resultado em até 2 pontos. Não pode transformar um resultado comum em crítico.',
    efeito: '+/-2 em resultado de dado',
    tags: ['mecânico', 'Armazenável'],
    tipoAtivacao: 'manual',
  },
  {
    id: 'foco-repentino',
    categoria: 'Vantagens Táticas',
    icone: '🎯',
    nome: 'Foco Repentino',
    custo: 9,
    descricao:
      'Antes de fazer uma rolagem importante, o jogador pode ativar esta trapaça. Ele rola 2 dados e fica com o melhor resultado.',
    efeito: 'Melhor de 2d6 em rolagem importante',
    tags: ['mecânico', 'Armazenável'],
    tipoAtivacao: 'manual',
  },
  {
    id: 'trapaceiro',
    categoria: 'Vantagens Táticas',
    icone: '🃏',
    nome: 'Trapaceiro',
    custo: 10,
    descricao: 'Permite rerolar qualquer dado em momentos críticos.',
    efeito: 'Rerrolar 1 dado (1x/sessão)',
    tags: ['mecânico', 'Armazenável'],
    tipoAtivacao: 'manual',
  },
  {
    id: 'furto-de-dados',
    categoria: 'Vantagens Táticas',
    icone: '🎯',
    nome: 'Furto de Dados',
    custo: 10,
    descricao: 'Após um sucesso, guarde até 3d6 para usar em rolagens futuras.',
    efeito: 'Guarda 3d6 para depois',
    tags: ['mecânico', 'Armazenável'],
    tipoAtivacao: 'manual',
  },
  {
    id: 'trato-feito',
    categoria: 'Vantagens Táticas',
    icone: '🤝',
    nome: 'Trato Feito',
    custo: 10,
    descricao: 'Durante negociações, role dados com o mestre para decidir o resultado.',
    efeito: 'Rola contra mestre em negociação',
    tags: ['mecânico', 'Armazenável'],
    tipoAtivacao: 'manual',
  },

  // ── Efeitos Avançados — limite de 1, armazenável ──
  {
    id: 'reflexo-instintivo',
    categoria: 'Efeitos Avançados',
    icone: '🛡️',
    nome: 'Reflexo Instintivo',
    custo: 17,
    descricao:
      'Após sofrer um ataque, o personagem pode reduzir o dano recebido em 30%. Só pode ser usado uma vez por combate.',
    efeito: '-30% dano (1x/combate)',
    tags: ['sorte', 'Combate'],
    tipoAtivacao: 'manual',
  },
  {
    id: 'azar-na-sorte',
    categoria: 'Efeitos Avançados',
    icone: '🌙',
    nome: 'Azar na Sorte',
    custo: 15,
    descricao: 'Uma vez por sessão, transforma um fracasso em sucesso.',
    efeito: 'Fracasso → Sucesso (1x/sessão)',
    tags: ['sorte', 'Sessão'],
    tipoAtivacao: 'manual',
  },
  {
    id: 'reversor',
    categoria: 'Efeitos Avançados',
    icone: '🔄',
    nome: 'Reversor',
    custo: 15,
    descricao: 'Transforma uma condição negativa em vantagem (+metade da dificuldade original).',
    efeito: 'Negativo → Vantagem temporária',
    tags: ['sorte', 'Sessão'],
    tipoAtivacao: 'manual',
  },
  {
    id: 'beneficiario-afortunado',
    categoria: 'Efeitos Avançados',
    icone: '🍀',
    nome: 'Beneficiário Afortunado',
    custo: 15,
    descricao: 'Evita uma situação perigosa ou mortal graças a um golpe de sorte.',
    efeito: 'Salva de situação mortal/perigosa',
    tags: ['sorte', 'Sessão'],
    tipoAtivacao: 'manual',
  },

  // ── Bênçãos Únicas — limite de 1, armazenável ──
  {
    id: 'instinto-de-sobrevivencia',
    categoria: 'Bênçãos Únicas',
    icone: '💀',
    nome: 'Instinto de Sobrevivência',
    custo: 19,
    descricao:
      'Quando um golpe reduziria o personagem a 0 de vida, ele permanece com 1 ponto de vida. Só pode acontecer uma vez por sessão.',
    efeito: 'Sobrevive com 1 HP (1x/sessão)',
    tags: ['Único', 'Sessão'],
    tipoAtivacao: 'manual',
  },
  {
    id: 'segundo-folego',
    categoria: 'Bênçãos Únicas',
    icone: '👼',
    nome: 'Segundo Fôlego',
    custo: 23,
    descricao:
      'Durante combate, o personagem recupera imediatamente 25% da vida máxima. Pode ser usado apenas uma vez por personagem.',
    efeito: '+25% HP em combate (1x/personagem)',
    tags: ['Único', 'Personagem'],
    tipoAtivacao: 'manual',
  },
  {
    id: 'sorte-de-principiante',
    categoria: 'Bênçãos Únicas',
    icone: '🌠',
    nome: 'Sorte de Principiante',
    custo: 20,
    descricao: 'Durante 3 turnos, todos os bônus de sorte são multiplicados por 1,5 (arredondado para cima).',
    efeito: 'Sorte ×1,5 (3 turnos)',
    tags: ['Único', 'Sessão'],
    tipoAtivacao: 'manual',
  },
  {
    id: 'escapada-milagrosa',
    categoria: 'Bênçãos Únicas',
    icone: '🕊️',
    nome: 'Escapada Milagrosa',
    custo: 20,
    descricao: 'Escapa por um triz de um ataque, armadilha ou efeito perigoso no último segundo.',
    efeito: 'Escape certo de 1 perigo',
    tags: ['Único', 'Sessão'],
    tipoAtivacao: 'manual',
  },
  {
    id: 'sorte-extrema',
    categoria: 'Bênçãos Únicas',
    icone: '⚡',
    nome: 'Sorte Extrema',
    custo: 25,
    descricao: 'Durante 10 minutos, +5 de sorte em TODAS as rolagens aplicáveis.',
    efeito: '+5 sorte (10 min)',
    tags: ['Único', 'Sessão'],
    tipoAtivacao: 'manual',
  },
  {
    id: 'abencoado-pelos-ceus',
    categoria: 'Bênçãos Únicas',
    icone: '🌟',
    nome: 'Abençoado pelos Céus',
    custo: 30,
    descricao: 'Rola 10d6 e guarda os 2 maiores para substituir rolagens futuras.',
    efeito: '10d6 → Guarda top 2 (sessão)',
    tags: ['Único', 'Sessão'],
    tipoAtivacao: 'manual',
  },
];

export const LIMITE_POR_CATEGORIA = {
  'Benefícios Menores': Infinity,
  'Vantagens Táticas': 2,
  'Efeitos Avançados': 1,
  'Bênçãos Únicas': 1,
};
